In [2]:
import jax
import jax.numpy as jnp

In [5]:
a = jnp.array([1,2])
b = jnp.array([2,2])
c=[a,b]
print(c)
print(*c)

[DeviceArray([1, 2], dtype=int32), DeviceArray([2, 2], dtype=int32)]
[1 2] [2 2]


In [77]:
import numpy as np
a=np.array(
[[[0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0]], 
 [[0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0]], 
 [[0, 0, 0], 
 [0, 8, 0], 
 [0, 0, 0]], 
 [[-2.52441, 0, 0.540302], 
 [0, 0, 0], 
 [0.540302, 0, 0]]]
)

print(a.transpose((2,0,1)))

b =np.asarray([[0, 0, 0], 
 [0, 0, 0.540302], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, -2.52441, 0], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, 8, 0], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0], 
 [0, 0.540302, 0]])

c = np.reshape(b,(3,5,3))
c=c.transpose((2,0,1))

d=np.reshape(c,(15,3))
print(d)

[[ 0.        0.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.       -2.52441   0.      ]
 [ 0.        8.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.540302]
 [ 0.        0.540302  0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.      ]
 [ 0.        0.        0.      ]]


In [82]:
a=[[1,2,3],[3,4]]
b=[1]
b.extend(a)
print(b)


[1, [1, 2, 3], [3, 4]]


In [69]:
from jax import grad, jacfwd


def f1(x,y):
    return jnp.asarray([x[0]*y[0], 5*x[2], x[2] * jnp.sin(x[0])])
def f2(x,y):
    return jnp.asarray([x[1]*y[1], 5*x[2], 4*x[1]**2 - 2*x[2], x[2] * jnp.cos(x[0])])
def g(f):    
    return lambda *xs: (print(xs),jnp.hstack(jax.jacfwd(f,argnums=[i for i in range(len(xs))])(*xs)))


In [70]:
from numpy import float32
a= [i for i in range(3)]
print(a)

print(jax.jacobian(f1)(jnp.asarray([1,2,3,4],dtype=float32),jnp.asarray([2,4],dtype=float32)))
print(jnp.hstack(jax.jacfwd(f1,argnums=[0,1])(jnp.asarray([1,2,3,4],dtype=float32),jnp.asarray([2,4],dtype=float32))))

xs = [jnp.asarray([1,2,3,4],dtype=float32),jnp.asarray([2,4],dtype=float32)]
g(f1)(*xs)



[0, 1, 2]
[[2.        0.        0.        0.       ]
 [0.        0.        5.        0.       ]
 [1.6209068 0.        0.841471  0.       ]]
[[2.        0.        0.        0.        1.        0.       ]
 [0.        0.        5.        0.        0.        0.       ]
 [1.6209068 0.        0.841471  0.        0.        0.       ]]
(DeviceArray([1., 2., 3., 4.], dtype=float32), DeviceArray([2., 4.], dtype=float32))


(None,
 DeviceArray([[2.       , 0.       , 0.       , 0.       , 1.       ,
               0.       ],
              [0.       , 0.       , 5.       , 0.       , 0.       ,
               0.       ],
              [1.6209068, 0.       , 0.841471 , 0.       , 0.       ,
               0.       ]], dtype=float32))

In [72]:
a = jnp.asarray([[1,2],[3,4]])
print(a)
a=jnp.reshape(a,(-1,))
print(a)
a=[1,2]
b=[2,3]
arg=[a,b]
print(*arg)

[[1 2]
 [3 4]]
[1 2 3 4]
[1, 2] [2, 3]


In [77]:
from jax.core import axis_frame
import numpy as np
import jax.numpy as jnp
import jax
def f(x,y):
    return jnp.asarray([x[0]*y[0], 5*x[2]+y[1], 4*x[1]**2+y[1]*y[2] - 2*x[2], jnp.exp(y[3]) + x[2] * jnp.sin(x[0]),x[1]*y[2]])

jnp_x = jnp.asarray([1,2,3],dtype=jnp.float32)
jnp_y = jnp.asarray([3,1,2,1.5],dtype=jnp.float32)
primals, f_vjp = jax.vjp(f, jnp_x, jnp_y)
a = jnp.eye(5, dtype=jnp.float32)
f_map = jax.vmap(f_vjp,in_axes=-1,out_axes=-1)
xbar, ybar = f_map(a)
print(xbar)
print(ybar)

#a = jnp.array([0.0, 0.0,0.0,0.0,0.0])
#b = jnp.array([[[1.0, 0.0,0.0],[1.0, 0.0,0.0],[1.0, 0.0,0.0],[1.0, 0.0,0.0],[1.0, 0.0,0.0]],[[1.0, 0.0,0.0],[1.0, 0.0,0.0],[1.0, 0.0,0.0],[1.0, 0.0,0.0],[1.0, 0.0,0.0]]])
#c = jnp.array([[[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0]],[[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0],[0.0, 0.0,0.0,0.0]]])

b = jnp.asarray(np.random.rand(3,5,35))
c = jnp.asarray(np.random.rand(4,5,35))
#primals, ff_vjp = jax.vjp(jax.vmap(f_vjp), a)
print(b.shape)
primals, ff_vjp = jax.vjp(f_map,a)
fm_vjp = jax.vmap(ff_vjp,in_axes=-1,out_axes=-1)
xbar = fm_vjp((b,c))
print(xbar)


[[ 3.         0.         0.         1.6209068  0.       ]
 [ 0.         0.        16.         0.         2.       ]
 [ 0.         5.        -2.         0.841471   0.       ]]
[[1.       0.       0.       0.       0.      ]
 [0.       1.       2.       0.       0.      ]
 [0.       0.       1.       0.       2.      ]
 [0.       0.       0.       4.481689 0.      ]]
(3, 5, 35)
(DeviceArray([[[ 1.8073775 ,  2.0410285 ,  2.2005014 ,  3.2541966 ,
                2.6697612 ,  2.677493  ,  1.9110144 ,  2.484357  ,
                3.3870332 ,  3.5677469 ,  2.6067436 ,  1.1328385 ,
                1.9704114 ,  2.1151583 ,  1.3997405 ,  2.284913  ,
                2.3046196 ,  2.2792587 ,  0.47807312,  1.1134357 ,
                2.8710184 ,  3.6035893 ,  2.5659573 ,  2.6748316 ,
                2.9134374 ,  1.8808324 ,  0.45597464,  0.84295774,
                1.0868913 ,  2.4888363 ,  1.4504968 ,  2.9593441 ,
                1.6110789 ,  3.3387725 ,  1.5050812 ],
              [ 0.0667814 ,  

In [97]:
from casadi import *
def f(x,y):
    return jnp.asarray([x[0]*y[0], 5*x[2]+y[1], 4*x[1]**2+y[1]*y[2] - 2*x[2], jnp.exp(y[3]) + x[2] * jnp.sin(x[0]),x[1]*y[2]])

x=[DM([1, 2, 3]), DM([3, 1, 2, 1.5]), DM([3, 16, 12, 7.0061, 4]), DM(
    [[1, 0, 0, 0, 0], 
 [0, 1, 0, 0, 0], 
 [0, 0, 1, 0, 0], 
 [0, 0, 0, 1, 0], 
 [0, 0, 0, 0, 1]])]

jarg = [jnp.squeeze(jnp.asarray(p)) for p in x]

n_in1=2
n_out1=1
rev_f = lambda x: jax.vmap(jax.vjp(f,*x[0:n_in1])[1],in_axes=-1,out_axes=-1)(*x[n_in1+n_out1:n_in1+2*n_out1] if n_out1==1 else tuple(x[n_in1+n_out1:n_in1+2*n_out1]))

return1 = rev_f(jarg)
#print(return1)

jarg.extend([jnp.asarray(r) for r in return1])
jarg.append(jnp.asarray(np.random.rand(3,5,35)))
jarg.append(jnp.asarray(np.random.rand(4,5,35)))
#print(jarg)

n_in=4
n_out=2
rev_f_f = lambda x: jax.vmap(jax.vjp(rev_f,x[0:n_in])[1],in_axes=-1,out_axes=-1)(tuple(x[n_in+n_out:n_in+2*n_out]))


return2 = rev_f_f(jarg)
print(len(return2[0]))
print(return2[0])

4
[DeviceArray([[ 0.7252479 , -0.6518867 , -0.5781406 , -0.42621607,
               0.11022168,  1.0472174 , -1.1192635 , -0.07666296,
               0.60549384, -1.2607276 , -1.323139  , -2.232508  ,
              -0.1577295 , -1.0478445 , -0.74898773,  0.42525053,
              -0.9651347 , -0.3343746 , -1.2774608 , -1.7874639 ,
              -0.0789668 , -0.84153306,  0.08873491, -1.5560231 ,
              -0.77913725, -0.6758762 , -1.1270168 ,  0.18018115,
               0.5500754 , -1.5331893 ,  0.6097779 , -1.2157482 ,
              -0.34683678, -1.1750741 , -0.06995225],
             [ 7.05471   ,  2.0645187 ,  4.101494  ,  3.7927816 ,
               0.26244044,  3.5306659 ,  2.9470303 ,  1.0410478 ,
               7.8473587 ,  7.45031   ,  2.4671838 ,  8.1941805 ,
               6.4635615 ,  7.756854  ,  6.6751537 ,  4.859329  ,
               3.6391406 ,  5.1273503 ,  2.0863473 ,  3.526178  ,
               8.44437   ,  6.6193924 ,  3.295836  ,  5.445667  ,
               5.53