In [2]:
import jax
import jax.numpy as jnp

In [5]:
a = jnp.array([1,2])
b = jnp.array([2,2])
c=[a,b]
print(c)
print(*c)

[DeviceArray([1, 2], dtype=int32), DeviceArray([2, 2], dtype=int32)]
[1 2] [2 2]


In [22]:
import numpy as np
a=np.array(
[[[0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0]], 
 [[0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0]], 
 [[0, 0, 0], 
 [0, 8, 0], 
 [0, 0, 0]], 
 [[-2.52441, 0, 0.540302], 
 [0, 0, 0], 
 [0.540302, 0, 0]]]
)

print(a.transpose((2,0,1)))


[[[ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [-2.52441   0.        0.540302]]

 [[ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        8.        0.      ]
  [ 0.        0.        0.      ]]

 [[ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.540302  0.        0.      ]]]


In [24]:
p = np.array([[[1,2],[4,4]]])
print(p)
print(p.squeeze())

[[[1 2]
  [4 4]]]
[[1 2]
 [4 4]]
