In [2]:
import jax
import jax.numpy as jnp

In [5]:
a = jnp.array([1,2])
b = jnp.array([2,2])
c=[a,b]
print(c)
print(*c)

[DeviceArray([1, 2], dtype=int32), DeviceArray([2, 2], dtype=int32)]
[1 2] [2 2]


In [22]:
import numpy as np
a=np.array(
[[[0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0]], 
 [[0, 0, 0], 
 [0, 0, 0], 
 [0, 0, 0]], 
 [[0, 0, 0], 
 [0, 8, 0], 
 [0, 0, 0]], 
 [[-2.52441, 0, 0.540302], 
 [0, 0, 0], 
 [0.540302, 0, 0]]]
)

print(a.transpose((2,0,1)))


[[[ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [-2.52441   0.        0.540302]]

 [[ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        8.        0.      ]
  [ 0.        0.        0.      ]]

 [[ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.        0.        0.      ]
  [ 0.540302  0.        0.      ]]]


In [69]:
from jax import grad, jacfwd


def f1(x,y):
    return jnp.asarray([x[0]*y[0], 5*x[2], x[2] * jnp.sin(x[0])])
def f2(x,y):
    return jnp.asarray([x[1]*y[1], 5*x[2], 4*x[1]**2 - 2*x[2], x[2] * jnp.cos(x[0])])
def g(f):    
    return lambda *xs: (print(xs),jnp.hstack(jax.jacfwd(f,argnums=[i for i in range(len(xs))])(*xs)))


In [70]:
from numpy import float32
a= [i for i in range(3)]
print(a)

print(jax.jacobian(f1)(jnp.asarray([1,2,3,4],dtype=float32),jnp.asarray([2,4],dtype=float32)))
print(jnp.hstack(jax.jacfwd(f1,argnums=[0,1])(jnp.asarray([1,2,3,4],dtype=float32),jnp.asarray([2,4],dtype=float32))))

xs = [jnp.asarray([1,2,3,4],dtype=float32),jnp.asarray([2,4],dtype=float32)]
g(f1)(*xs)



[0, 1, 2]
[[2.        0.        0.        0.       ]
 [0.        0.        5.        0.       ]
 [1.6209068 0.        0.841471  0.       ]]
[[2.        0.        0.        0.        1.        0.       ]
 [0.        0.        5.        0.        0.        0.       ]
 [1.6209068 0.        0.841471  0.        0.        0.       ]]
(DeviceArray([1., 2., 3., 4.], dtype=float32), DeviceArray([2., 4.], dtype=float32))


(None,
 DeviceArray([[2.       , 0.       , 0.       , 0.       , 1.       ,
               0.       ],
              [0.       , 0.       , 5.       , 0.       , 0.       ,
               0.       ],
              [1.6209068, 0.       , 0.841471 , 0.       , 0.       ,
               0.       ]], dtype=float32))

In [72]:
a = jnp.asarray([[1,2],[3,4]])
print(a)
a=jnp.reshape(a,(-1,))
print(a)
a=[1,2]
b=[2,3]
arg=[a,b]
print(*arg)

[[1 2]
 [3 4]]
[1 2 3 4]
[1, 2] [2, 3]
